name: selectable
description: A Flutter widget that enables text selection over all the text widgets it contains.
version: 0.3.0
repository: https://github.com/ronjb/selectable

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  characters: ^1.4.0
  collection: ^1.19.1
  equatable: ^2.0.7
  float_column: ^3.0.0
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints_plus: ^3.2.0
  flutter_test:
    sdk: flutter
